# take by ground
# https://github.com/laddison/docker-compose-php-nginx-mysql-redis

version: "3"
services:

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/web:/var/www/html
    ports:
      - "7880:80"
    links:
      - php:php

  php:
    build: ./php
    expose:
      - "9000"
    links:
      - mysql
      - redis
    volumes:
      - ./www/web:/var/www/html

  mysql:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "7306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis
    ports:
      - "7379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1


